apiVersion: v1
kind: Service
metadata:
  name: a-service
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
    nodePort: 30037
  selector:
    run: service-a
